name: Create GCP Project

on:
  push:
    branches: [ main ] # Or your branch

jobs:
  create-project:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for workload identity federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/pvenkatesh-sandbox-01/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@pvenkatesh-sandbox-01.iam.gserviceaccount.com

      - name: Create GCP project
        run: |
          gcloud projects create new-project-id \
            --set-name="testproj" # Replace with desired name
            --organization=702407671690 # If applicable
